name: rio
version: 0.0.0.0

dependencies:
- base
- bytestring
- clock # FIXME perhaps drop
- conduit # FIXME drop
- conduit-extra # FIXME drop
- containers
- deepseq
- directory
- exceptions
- filepath
- hashable
- microlens # FIXME perhaps drop
- microlens-mtl # FIXME perhaps drop
- mtl
- path-io # FIXME drop
- path
- store # FIXME drop
- text
- time
- typed-process >= 0.2.1.0
- unliftio
- unordered-containers
- vector

when:
- condition: os(windows)
  then:
    cpp-options: -DWINDOWS
    dependencies:
    - Win32
  else:
    dependencies:
    - pid1 # FIXME drop, likely move code in here or typed-process
    - unix

library:
  source-dirs: src/
  other-modules:
  - RIO.Prelude
