FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
  ca-certificates \
  libgmp-dev \
  build-essential \
  libnss3 \ 
  libnss-lwres \
  libnss-mdns \
  git-all \
  curl

COPY testbuild1 /testbuild1
COPY testbuild2 /testbuild2

ENV PATH="/:${PATH}"
