stack-sit:
  image: mystack:latest
  command: bash -c "cd testbuild1 && time stack build --allow-different-user --stack-root $PWD/root && distributed sit 127.0.0.1 5000"
  tty: true
  stdin_open: true
  net: "host"
  ports: 
    - "5000:5000"
stack-build:
  image: mystack:latest
  command: bash -c "cd testbuild1 && rm -rf .stack-work && distributed build 127.0.0.1 5001 && time stack build --allow-different-user --stack-root $PWD/root" 
  tty: true
  stdin_open: true
  net: "host"
  ports:
    - "5001:5001"
