FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
  ca-certificates \
  libgmp-dev \
  build-essential \
  libnss3 \ 
  libnss-lwres \
  libnss-mdns \
  git-all \
  curl

RUN git clone https://github.com/McGizzle/testbuild 
ENV PATH="/:${PATH}"
