FROM ubuntu

RUN mkdir /app

WORKDIR /app

RUN apt-get update && apt-get install -y \
  ca-certificates \
  libgmp-dev \
  build-essential \
  libnss3 \ 
  libnss-lwres \
  libnss-mdns \
  git-all

RUN git clone https://github.com/McGizzle/testbuild 

ENV PATH="/app:${PATH}"
