flags:
  mintty:
    win32-2-5: false
  stack:
    hide-dependency-versions: true
    supported-build: true
nix:
  packages:
  - zlib
  enable: false
packages:
- .
- subs/rio
- custom/path
- custom/typed-process
extra-deps:
- Cabal-2.0.1.0
- ansi-terminal-0.8
- ansi-wl-pprint-0.6.8.2
- bindings-uname-0.1
- conduit-extra-1.2.3.1
- distributed-process-0.7.3
- distributed-process-simplelocalnet-0.2.4
- extra-1.6
- hpack-0.20.0
- mintty-0.1.1
- network-transport-0.5.2
- network-transport-tcp-0.6.0
  #- path-0.6.1
- path-io-1.3.3
- smallcheck-1.1.3
#- typed-process-0.2.1.0
- unliftio-0.2.1.0
- cborg-0.2.0.0
resolver: lts-9.14
