resolver: lts-9.14
packages:
- .
- subs/rio
- subs/distributed

docker:
  enable: false
image:
  container:
    name: "mystack"
    base: "mystack-base"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
  mintty:
    win32-2-5: false
extra-deps:
- Cabal-2.0.1.0
- mintty-0.1.1
- bindings-uname-0.1
- path-0.6.1
- path-io-1.3.3
- extra-1.6
- hsc2hs-0.68.2
- hpack-0.21.0
- unliftio-0.2.1.0
- smallcheck-1.1.3
- conduit-extra-1.2.3.1
- typed-process-0.2.1.0

# https://github.com/commercialhaskell/stack/issues/3785
- ansi-terminal-0.8
- ansi-wl-pprint-0.6.8.2
