name:                distributed
version:             0.1.0.0
license:             BSD3
author:              "Sean McGroarty"
maintainer:          "mcgroas@tcd.ie"
copyright:           "2018 Sean McGroarty"

extra-source-files:

description:         Please see the README on Github at <https://github.com/McGizzle/simple#readme>

dependencies:
- base >= 4.7 && < 5
- distributed-process
- distributed-process-simplelocalnet
- pipes
- pipes-safe
- dirstream
- system-fileio
- system-filepath
- ansi-terminal
- Cabal
- bytestring
- exceptions
- filepath
- directory
- async
- text

library:
  source-dirs: src

tests:
  simple-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed

