name:                distributed
version:             0.1.0.0
license:             BSD3
author:              "Sean McGroarty"
maintainer:          "mcgroas@tcd.ie"
copyright:           "2018 Sean McGroarty"

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates

dependencies:
- base >= 4.7 && < 5
- distributed-process
- distributed-process-simplelocalnet
- pipes
- pipes-safe
- dirstream
- system-fileio
- system-filepath
- ansi-terminal
- Cabal
- bytestring
- temporary
- exceptions
- filepath
- directory
- async
- text
- process
- binary

library:
  source-dirs: src
  exposed-modules: Distributed

executables:
  FTN:
    source-dirs: src
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: 
    - distributed

tests:
  distributed-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed
    - hspec

